<?php

namespace UserBundle\Repository;

/**
 * categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNomParameter($id){
        $query = $this->getEntityManager()
            ->createQuery("
                    select categorie from UserBundle:categorie categorie WHERE categorie.id=:id
            ")
            ->setParameter('id',$id);
        return $query->getResult();
    }
}
