<?php

namespace UserBundle\Repository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCommIdParameter($id){
        $query = $this->getEntityManager()
            ->createQuery("select c from UserBundle:Commentaire c 
            where c.experience=:id")
            ->setParameter('id',$id);
        return $query->getResult();
    }

    public function countComments($id){
        $query = $this->getEntityManager()
            ->createQuery("
            select count(c) 
            from UserBundle:Commentaire c 
            where c.experience=:(
            select e from UserBundle:Experience e 
            where e.id=:id)")
            ->setParameter('id',$id);
        return $query->getResult();
    }
}
