<?php

namespace UserBundle\Repository;

/**
 * CommentaireEvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireEvenementRepository extends \Doctrine\ORM\EntityRepository
{
}
