<?php

namespace UserBundle\Repository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findIdParameter($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("select p from UserBundle:Experience p 
            where p.id=:id")
            ->setParameter('id', $id);
        return $query->getResult();
    }

    public function findByNameParameter($nom)
    {
        $query = $this->getEntityManager()
            ->createQuery("select e from UserBundle:Experience e 
            where e.nomExp like :e.nomExp")
            ->setParameter('nomExp', '%' . $nom . '%');
        return $query->getResult();
    }

    public function findExpByCatParameter($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("select c from UserBundle:Experience c 
            where c.categorie=:id")
            ->setParameter('id', $id);
        return $query->getResult();
    }

    public function findExpByUserParameter($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("select c from UserBundle:Experience c 
            where c.user=:id")
            ->setParameter('id', $id);
        return $query->getResult();
    }

    public function findByNameExpParameter($nom)
    {
        $query = $this->getEntityManager()
            ->createQuery("select exp from UserBundle:Experience exp where
             exp.nomExp=:nomExp")
        ->setParameter('nomExp', $nom);
        return $query->getResult();
    }

    public function topExp(){
        $query= $this->createQueryBuilder('e')
            ->orderBy('e.singularViewCount', 'DESC')->setMaxResults(3);
        return $query->getQuery()->getResult();
    }
}

