<?php

namespace UserBundle\Repository;

/**
 * forumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class forumRepository extends \Doctrine\ORM\EntityRepository
{
    public function findCategorieParameter($id){
        $query = $this->getEntityManager()
            ->createQuery("
                    select forum from UserBundle:forum forum WHERE forum.categorie=:id
            ")
            ->setParameter('id',$id);
        return $query->getResult();
    }

    public function findforumParameter($id){
        $query = $this->getEntityManager()
            ->createQuery("
                    select forum from UserBundle:forum forum WHERE forum.id=:id
            ")
            ->setParameter('id',$id);
        return $query->getResult();
    }

    public function findQuesByUserParameter($id)
    {
        $query = $this->getEntityManager()
            ->createQuery("select c from UserBundle:forum c 
            where c.user=:id")
            ->setParameter('id', $id);
        return $query->getResult();
    }



}
