<?php

namespace UserBundle\Repository;

/**
 * MessageMetaataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageMetaataRepository extends \Doctrine\ORM\EntityRepository
{
}
