<?php

namespace UserBundle\Repository;

/**
 * ThreadMetaDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThreadMetaDataRepository extends \Doctrine\ORM\EntityRepository
{
}
