// <auto-generated />
namespace CloudKids.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class test : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(test));
        
        string IMigrationMetadata.Id
        {
<<<<<<< HEAD:CloudKids.Data/Migrations/202003181817496_test.Designer.cs
            get { return "202003181817496_test"; }
=======
            get { return "202003172017573_test"; }
>>>>>>> 4cfe8c2585d81b418f9612a509895ee167cd36d5:CloudKids.Data/Migrations/202003172017573_test.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
