<?php

namespace ProduitBundle\Repository;

/**
 * CategorieProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
