<?php

namespace ProduitBundle\Repository;

/**
 * lignedepanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class lignedepanierRepository extends \Doctrine\ORM\EntityRepository
{
}
