<?php

namespace ProduitBundle\Repository;

/**
 * LikeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeProduitRepository extends \Doctrine\ORM\EntityRepository
{

    public function getTopProduct(){

        $query= $this->createQueryBuilder('s')
            ->select('l, count(l.id) AS HIDDEN nbLike')
            ->from('ProduitBundle:LikeProduit', 'l')
            ->groupBy('l.id')
            ->orderBy("nbLike", 'DESC');

        return $query->getQuery()->getResult();
    }

}

