<?php

namespace ProduitBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategorieProduct($key,$id_categorie){

        $query= $this->createQueryBuilder('p')
            ->join('p.souscategorie', 's')
            ->join('s.categorie', 'c')
            ->where('c.id=:cp')
            ->andWhere('p.libelle LIKE :key')
            ->setParameters(array('cp'=> $id_categorie, 'key' => '%'.$key.'%'));

        return $query->getQuery()->getResult();
    }

    public function findByCategorie($id){

        $query= $this->createQueryBuilder('p')
            ->join('p.souscategorie', 's')
            ->join('s.categorie', 'c')
            ->where('c.id=:id')
            ->setParameter('id', $id);

        return $query->getQuery()->getResult();
    }


    public function getSousCategorieProduct($key,$id_souscategorie){

        $query= $this->createQueryBuilder('p')
            ->join('p.souscategorie', 's')
            ->where('s.id=:s')
            ->andWhere('p.libelle LIKE :key')
            ->setParameters(array('s'=> $id_souscategorie, 'key' => '%'.$key.'%'));

        return $query->getQuery()->getResult();
    }


    public function getProduct($key){

        $query= $this->createQueryBuilder('p')
            ->where('p.libelle LIKE :key')
            ->setParameter('key' , '%'.$key.'%');

        return $query->getQuery()->getResult();
    }

    public function getRandom(){
        $max = $this->_em->createQuery('SELECT MAX(p.id)
                                FROM ProduitBundle:Produit p'
        )->getSingleScalarResult();

        $query = $this->_em->createQuery('SELECT p
                               FROM ProduitBundle:Produit p
                               WHERE p.id >= :rand')->setParameter('rand' , rand(0,$max))
            ->setMaxResults(12);

        return $query->getResult();
    }

    public function findByOrder(){

         $query= $this->createQueryBuilder('p')
             ->orderBy('p.id', 'DESC');
        return $query->getQuery()->getResult();
    }


    public function getBestSeller(){

        $query= $this->createQueryBuilder('p')
            ->orderBy('p.prix', 'ASC');

        return $query->getQuery()->getResult();
    }




}
