<?php

namespace ProduitBundle\Repository;

/**
 * SousCategorieProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SousCategorieProduitRepository extends \Doctrine\ORM\EntityRepository
{
}
