imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@ExperienceBundle/Resources/config/services.yml" }
    - { resource: "@EvenementBundle/Resources/config/services.yml" }
    - { resource: "@ProduitBundle/Resources/config/services.yml" }
    - { resource: "@GroupBundle/Resources/config/services.yml" }
    - { resource: "@ContactBundle/Resources/config/services.yml" }
    - { resource: "@AdminBundle/Resources/config/services.yml" }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@ApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~

    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true


    templating:
        engines: ['twig']

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    port: '%mailer_port%'
    encryption: '%mailer_encryption%'

sensio_framework_extra:
   router:
        annotations: false


fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: UserBundle\Entity\User
    from_email:
        address: "yassine.lahbib@esprit.tn"
        sender_name: "worldfriendship"

#vich bundle upload
vich_uploader:
    db_driver: orm

    mappings:
        event_affiche:
            uri_prefix: /web/Evenement/image/affiches
            upload_destination: '%kernel.project_dir%/web/Evenement/image/affiches'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        experience_image:
            uri_prefix: /assets/img/experience/uploads
            upload_destination: '%kernel.project_dir%/web/assets/img/experience/uploads'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        categorie_image:
            uri_prefix: /assets/img/categorie
            upload_destination: '%kernel.project_dir%/web/assets/img/categorie'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        produit_image:
            uri_prefix: /assets/img/product
            upload_destination: '%kernel.project_dir%/web/assets/img/product'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

# Windows configuration
knp_snappy:
    pdf:
        enabled:    true
        # If you have wkhtmltopdf as an environment variable you don't need to provide the
        # full path to the executable, use it in the same way as you use in the console
        #binary:  "wkhtmltopdf"
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:    []
    image:
        enabled:    true
        binary:     "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltoimage.exe\""
        options:    []
        
fos_message:
    db_driver: orm
    thread_class: UserBundle\Entity\Thread
    message_class: UserBundle\Entity\Message

cengizhan_views_counter:
    use_query_builder: true


knp_paginator:

  template:
    pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v3_pagination.html.twig'     # sliding pagination controls template
    sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # sort link template

nomaya_social:
  buttons:
    facebook:
      url:            null
      locale:         "fr_FR"
      send:           false
      width:          300
      showFaces:      false
      layout:         "button_count"
    twitter:
      url:            null
      locale:         "fr"
      message:        "Je veux partager ça avec vous"
      text:           "Tweet"
      via:            "L'Equipe cartedevisitevirtuelle.fr"
      tag:            "ttot"
    googleplus:
      url:            null
      locale :        "fr"
      size :          "medium"
      annotation :    "bubble"
      width :         300
    linkedin:
      url:            null
      locale:         "fr_FR"
      counter:        "right"
    pinterest:
      url:            null
  links:
    facebook:           "http://www.facebook.com/yann.chauvel"
    googleplus:         "https://plus.google.com/105931415830389032796"
  theme:                  'default' # optional
